safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: [ '_DOCS', '_SCRIPTS', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md' ]
sass:
  style: compressed
encoding: UTF-8

plugins:
  - jekyll-assets
  - jekyll-sitemap

url: http://17cng2020.lnec.pt
baseur: ""

# Configuration for site
title: "17cng2020"
logo:
  image: images/17cng2021.gif
  info: 17CNG 2020, LNEC, Lisboa

google_analytics_id: UA-144463477-1

### Note. Uncomment and update spreadsheet parameters to enable pulling program
###       data from Google Sheet(s)
program:
  #   # If the specified file doesn't exist, there will be command-line dialog to create it
  #   # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
  google_client_id: .travis.d/CNG-google_client.id.json
  #   # Google spreadsheet with the conference data
  spreadsheet:
    - "1gNA03qkdmw4TITKLAGBijIY-zVNOwLFjqeeU5JWHNzk"  #17CNG Programs

## Configuration for menu.html
menu:
  - name: Início
    url: /
    icon: fa-home
  - name: Programa
    icon: fa-calendar
    submenu:
      - name: Programa geral
        url: /program.html
        icon: fa-calendar
      - name: Domingo
        url: /program_sunday.html
        icon: fa-calendar
      - name: Segunda
        url: /program_monday.html
        icon: fa-calendar
      - name: Terça
        url: /program_tuesday.html
        icon: fa-calendar
      - name: Quarta
        url: /program_wednesday.html
        icon: fa-calendar
  - name: 17CNG
    icon: fa-briefcase
    submenu:
      - name: Objetivos e temas
        url: /objectives-CNG.html
        icon: fa-bullseye
      - name: Instruções para submissão
        url: /submission-CNG.html
        icon: fa-pencil
  - name: 10CLBG
    icon: fa-briefcase
    submenu:
      - name: Objetivos
        url: /objectives-CLBG.html
        icon: fa-bullseye
      - name: Instruções para submissão
        url: /submission-CLBG.html
        icon: fa-pencil
  - name: Apelo a comunicações
    url: /call-papers-CNG.html
    icon: fa-bullhorn
  - name: Artigos aceites
    url: /accepted-papers.html
    icon: fa-check-square
  - name: VII Lição Victor de Mello
    url: /licao-victor-mello.html
    icon: fa-university
  - name: 11EJG
    url: /jovens-geo.html
    icon: fa-graduation-cap
  - name: Palestrantes convidados
    url: /keynote_speakers.html
    icon: fa-street-view
  - name: Inscrição
    icon: fa-user-plus
    url: /registration.html
  - name: Prémio Teixeira Duarte
    icon: fa-trophy
    url: /premio-teixeira-duarte.html
  - name: Empresas
    icon: fa-handshake-o
    submenu:
      - name: Patrocinadores
        icon: fa-pencil
        url: /supporters.html
  #  - name: Expositores
  #    icon: fa-eye
  #    url: /stands.html
  #- name: Alojamento
  #  icon: fa-building-o
  #  url: /hoteis.html
  - name: Visitas técnicas virtuais
    icon: fa-map-signs
    url: /technical_visits.html
  - name: Eventos sociais
    icon: fa-calendar
    submenu:
      - name: Receção
        icon: fa-glass
        url: /reception.html
  #  - name: Banquetes
  #    icon: fa-cutlery
  #    url: /banquet.html
  - name: Local
    url: /lnec.html
    icon: fa-map-marker
  - name: Comissões-17CNG
    icon: fa-users
    submenu:
      - name: Comissão de Honra
        url: /committie_honra_CNG.html
        icon: fa-users
      - name: Comissão de Acompanhamento
        url: /committie_acomp_CNG.html
        icon: fa-users
      - name: Comissão Organizadora
        url: /committie_org_CNG.html
        icon: fa-users
      - name: Comissão Científica
        url: /committie_cientifica_CNG.html
        icon: fa-users
  - name: Comissões-10CLBG
    icon: fa-users
    submenu:
      - name: Comissão Organizadora
        url: /committie_org_CLBG.html
        icon: fa-users
      - name: Comissão Científica
        url: /committie_cientifica_CLBG.html
        icon: fa-users
  #- name: Informações úteis
  #  icon:  fa-map-pin
  #  submenu:
  #  - name: Chegar ao LNEC
  #    url: /getting_LNEC.html
  #    icon: fa-car
  #  - name: Mobilidade partilhada
  #    url: /mobility.html
  #    icon: fa-bicycle
  #  - name: Sobre Lisboa
  #    url: /getting_around.html
  #    icon: fa-compass
  #  - name: Adiamento
  #    url: /adiamento.html
  #    icon: fa-eraser
  #- name: Aplicação Android/iOS
  #  url: /mobileApp.html
  #  icon: fa-android
  - name: Contactos
    url: /contacts.html
    icon: fa-address-book


colors:
  highlight: aaaaaa
  highlight-darker: f9e90c
  hfont: ffffff

  program:
    break-background: d1d1d1

# Set to True when ready to show Live Streaming links in the program
enable_remote: false

assets:
  cache: .sass-cache
  features:
    automatic_img_size: false

  sources:
    - css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"